project_name: data-server
builds:
    goos:
      - linux
    goarch:
      - amd64
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - data-server
    image_templates:
      - 'ghcr.io/iptecharch/test-image:v{{ .Version }}'
    dockerfile: Dockerfile
    skip_push: false
  - goos: linux
    goarch: amd64
    ids:
      - data-server
    image_templates:
      - 'registry.k8s.hans.io/iptecharch/data-server:v{{ .Version }}'
    dockerfile: Dockerfile
    skip_push: false
    push_flags:
      - --tls-verify=false
nightly:
  name_template: 'v0.0.0-{{ .ShortCommit }}'
  tag_name: devel
  publish_release: false
  keep_single_release: false
