project_name: data-server
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - data-server
    image_templates:
      - "ghcr.io/iptecharch/test-image:{{ .Env.VERSION }}"
    dockerfile: Dockerfile
    skip_push: false
  - goos: linux
    goarch: amd64
    ids:
      - data-server
    image_templates:
      - "registry.k8s.hans.io/iptecharch/data-server:{{ .Env.VERSION }}"
    dockerfile: Dockerfile
    skip_push: false
    push_flags:
      - --tls-verify=false

