name: install robot

on: 
  workflow_dispatch:

jobs:
  create-cluster:
    runs-on: kind
    steps:
      - name: Checkout integration-tests
        uses: actions/checkout@v4
        with:
          path: integration-tests

      - name: Checkout config-server
        uses: actions/checkout@v4
        with:
          ref: ${{ env.CONFIG_VERSION }}
          path: config-server
          repository: iptecharch/config-server
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: "integration-tests/tests/requirements.txt"

      - name: Install robotframework
        run: |
          pip install -r integration-tests/tests/requirements.txt

