name: dev-build-nightlies

on:
  schedule:
    - cron: "5 20 * * *"
  workflow_dispatch:

env:
    GOVER: 1.21.4

jobs:
  dev-release:
    runs-on: iptecharch-action-runners
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: iptecharch/cache
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          fetch-depth: 0

      # Make sure the @v0.8.0 matches the current version of the action
      - uses: webfactory/ssh-agent@v0.8.0
        with:
            ssh-private-key: ${{ secrets.IPTECHARCH_SSH_KEY }}

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOVER }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Private k8s Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.k8s.hans.io
          username: iptecharch-builder
          password: ${{ secrets.K8S_REGISTRY_HANS }}

      - name: debug
        run: sleep 3600
        
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --clean -f .goreleaser.nightlies.yml --skip=validate
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}
