name: dev-build-nightlies

on:
  schedule:
    - cron: "5 20 * * *"
  workflow_dispatch:

env:
    GOVER: 1.21.4

jobs:
  dev-release:
    runs-on: iptecharch-action-runners
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: iptecharch/cache
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          fetch-depth: 0

      # Make sure the @v0.8.0 matches the current version of the action
      - uses: webfactory/ssh-agent@v0.8.0
        with:
            ssh-private-key: ${{ secrets.IPTECHARCH_SSH_KEY }}
        
      - name: Setup Git config
        run: |
          git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"
          mkdir -p -m 0700 /home/runner/.ssh && ssh-keyscan github.com >> /home/runner/.ssh/known_hosts
          
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOVER }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: kubernetes
          driver-opts: |
            namespace=github-actions-runners
            replicas=1
          install: true
          endpoint: "unix:///var/run/docker.sock"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Private k8s Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.k8s.hans.io
          username: iptecharch-builder
          password: ${{ secrets.K8S_REGISTRY_HANS }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        continue-on-error: true
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --clean -f .goreleaser.nightlies.yml --skip=validate
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      - name: debug
        run: sleep 600
