name: dev-build-goreleaser

on: workflow_dispatch

env:
  GOVER: 1.21.4

jobs:
  dev-release:
    runs-on: iptecharch-action-runners
    steps:
      - name: Checkout data-server
        uses: actions/checkout@v4
        with:
          repository: iptecharch/data-server
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          fetch-depth: 0

      # Make sure the @v0.8.0 matches the current version of the action
      - uses: webfactory/ssh-agent@v0.8.0
        with:
            ssh-private-key: ${{ secrets.IPTECHARCH_SSH_KEY }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: iptecharch-builder
          password: ${{ secrets.GH_PAT }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}

