name: create kind on k8s

on: workflow_dispatch

jobs:
  create-cluster:
    runs-on: iptecharch-action-runners
    container: 
      image: docker:dind
      ports:
        - 6443
      args:
       - dockerd
       - --host=unix:///run/docker/docker.sock
       - --group=$(DOCKER_GROUP_GID)
      env:
       - name: DOCKER_GROUP_GID
         value: "123"
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: ci-test
