name: test-git-tags

on: workflow_dispatch

env:
  GOVER: 1.21.4

jobs:
  get-tag:
    runs-on: iptecharch-action-runners
    strategy:
      fail-fast: false
      matrix:
        repository: ["schema-server", "data-server", "cache", "config-server"]
    outputs:
      git_tag: ${{ steps.git_tag.outputs.git_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: "iptecharch/${{ matrix.repository }}"
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT

      - name: Get git tag
        id: git_tag
        run: |
          echo "${{ matrix.repository }}=$(git describe --tags --long --candidates 100)" >> $GITHUB_OUTPUT

  build:
    runs-on: iptecharch-action-runners
    needs:
      - get-tag
    steps:
      - name: Checkout integration-tests
        uses: actions/checkout@v4
        with:
          path: integration-tests
      - name: echo output
        run: echo '${{ toJSON(needs.git-tag.outputs) }}'
      - name: Debug 1
        run: ls -al
      - name: Debug 2
        run: ls -al */
