name: Create Cluster

on: workflow_dispatch

jobs:
  create-cluster:
    runs-on: kind
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: ci-test
